version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - wget https://github.com/jgm/pandoc/releases/download/3.1.5/pandoc-3.1.5-linux-amd64.tar.gz
      - mkdir /home/docs/pandoc
      - tar -xvzf pandoc-3.1.5-linux-amd64.tar.gz --strip-components 1 -C /home/docs/pandoc
      - PATH="/home/docs/pandoc/bin:$PATH"
      - echo $PATH
      - echo $(which pandoc)
      - echo $(whereis pandoc)

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
    - requirements: docs/source/requirements.txt
    - requirements: requirements.txt
sphinx:
  configuration: docs/source/conf.py